### ISSUE TITLE
[BUG]: yolox service cannot connect to the Open Telemetry service

### ISSUE THREAD

**Issue by filippo82** [NVIDIA/nv-ingest#297]
### Version

24.10

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

I am trying to reproduce the NVIDIA Multimodal PDF Data Extraction Blueprint on an instance in brev.dev.

After spinning up the blueprint with `docker compose --profile retrieval up --build`, the `yolox` service will keep throwing the error shown in the section below.

I believe the issue is that the `config/otel-collector-config.yaml` configuration file is missing the `http` info in the `receivers` section.

This is the current configuration:

```yaml
receivers:
  otlp:
    protocols:
      grpc:

...
```

and this is what it should look like:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

...
```

### Minimum reproducible example

```shell
Follow the instructions in the Notebook: https://github.com/NVIDIA/nv-ingest/blob/main/deploy/pdf-blueprint.ipynb
```

### Relevant log output

```shell
nv-ingest-yolox-1  | "timestamp": "2024-12-18 15:09:36,347", "level": "ERROR", "message": "I1218 15:09:36.347738 159 http_server.cc:4578] "HTTP request: 0 /v2/health/ready""
nv-ingest-yolox-1  | INFO:     172.18.0.9:38400 - "GET /v1/health/ready HTTP/1.1" 200 OK
nv-ingest-yolox-1  | Exception while exporting Span batch.
nv-ingest-yolox-1  | Traceback (most recent call last):
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 199, in _new_conn
nv-ingest-yolox-1  |     sock = connection.create_connection(
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
nv-ingest-yolox-1  |     raise err
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
nv-ingest-yolox-1  |     sock.connect(sa)
nv-ingest-yolox-1  | ConnectionRefusedError: [Errno 111] Connection refused
nv-ingest-yolox-1  |
nv-ingest-yolox-1  | The above exception was the direct cause of the following exception:
nv-ingest-yolox-1  |
nv-ingest-yolox-1  | Traceback (most recent call last):
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 789, in urlopen
nv-ingest-yolox-1  |     response = self._make_request(
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 495, in _make_request
nv-ingest-yolox-1  |     conn.request(
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 441, in request
nv-ingest-yolox-1  |     self.endheaders()
nv-ingest-yolox-1  |   File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
nv-ingest-yolox-1  |     self._send_output(message_body, encode_chunked=encode_chunked)
nv-ingest-yolox-1  |   File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
nv-ingest-yolox-1  |     self.send(msg)
nv-ingest-yolox-1  |   File "/usr/lib/python3.10/http/client.py", line 976, in send
nv-ingest-yolox-1  |     self.connect()
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 279, in connect
nv-ingest-yolox-1  |     self.sock = self._new_conn()
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 214, in _new_conn
nv-ingest-yolox-1  |     raise NewConnectionError(
nv-ingest-yolox-1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f87ff3e59f0>: Failed to establish a new connection: [Errno 111] Connection refused
nv-ingest-yolox-1  |
nv-ingest-yolox-1  | The above exception was the direct cause of the following exception:
nv-ingest-yolox-1  |
nv-ingest-yolox-1  | Traceback (most recent call last):
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 667, in send
nv-ingest-yolox-1  |     resp = conn.urlopen(
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 843, in urlopen
nv-ingest-yolox-1  |     retries = retries.increment(
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 519, in increment
nv-ingest-yolox-1  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
nv-ingest-yolox-1  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='otel-collector', port=4318): Max retries exceeded with url: /v1/traces (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87ff3e59f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
nv-ingest-yolox-1  |
nv-ingest-yolox-1  | During handling of the above exception, another exception occurred:
nv-ingest-yolox-1  |
nv-ingest-yolox-1  | Traceback (most recent call last):
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/opentelemetry/sdk/trace/export/__init__.py", line 367, in _export_batch
nv-ingest-yolox-1  |     self.span_exporter.export(self.spans_list[:idx])  # type: ignore
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 145, in export
nv-ingest-yolox-1  |     resp = self._export(serialized_data)
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 114, in _export
nv-ingest-yolox-1  |     return self._session.post(
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 637, in post
nv-ingest-yolox-1  |     return self.request("POST", url, data=data, json=json, **kwargs)
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
nv-ingest-yolox-1  |     resp = self.send(prep, **send_kwargs)
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
nv-ingest-yolox-1  |     r = adapter.send(request, **kwargs)
nv-ingest-yolox-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 700, in send
nv-ingest-yolox-1  |     raise ConnectionError(e, request=request)
nv-ingest-yolox-1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='otel-collector', port=4318): Max retries exceeded with url: /v1/traces (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87ff3e59f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by filippo82** [comment]
FYI, I took the changes from the [official OpenTelemetry docs](https://opentelemetry.io/docs/collector/configuration/).
